name: Export iOS

on:
  workflow_dispatch:  # Run manually from GitHub interface

jobs:
  export:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Godot
        run: |
          brew install --cask godot
          
      - name: Export iOS project
        run: |
          mkdir -p build/ios
          godot --headless --export "iOS" "build/ios/GodotPacman.xcarchive" --export-debug
          
      - name: Create IPA structure 
        run: |
          cd build/ios
          mkdir -p Payload
          cp -r GodotPacman.xcarchive/Products/Applications/GodotPacman.app Payload/
          zip -r GodotPacman.zip Payload
          mv GodotPacman.zip GodotPacman.ipa
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: |
            build/ios/GodotPacman.xcarchive
            build/ios/GodotPacman.ipa
