name: Export iOS

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]  # Optional: Trigger on pushes to main

jobs:
  export:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Godot with Mono
        run: |
          # Try multiple ways to get Godot with Mono
          echo "Attempting to download Godot Mono..."
          
          # Try direct download first with retry logic
          DOWNLOAD_ATTEMPTS=0
          MAX_ATTEMPTS=3
          SUCCESS=false
          
          while [ $DOWNLOAD_ATTEMPTS -lt $MAX_ATTEMPTS ] && [ "$SUCCESS" = false ]; do
            DOWNLOAD_ATTEMPTS=$((DOWNLOAD_ATTEMPTS+1))
            echo "Download attempt $DOWNLOAD_ATTEMPTS of $MAX_ATTEMPTS"
            
            curl -L --connect-timeout 30 --retry 5 --retry-delay 10 \
              -o godot.zip \
              "https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_mono_macos_universal.zip"
            
            # Verify the download was successful
            if [ -f godot.zip ] && [ $(stat -f%z godot.zip) -gt 1000000 ]; then
              echo "Download appears successful, verifying ZIP integrity..."
              if unzip -t godot.zip > /dev/null 2>&1; then
                echo "ZIP file is valid!"
                SUCCESS=true
              else
                echo "ZIP file is corrupted, retrying download..."
                rm godot.zip
              fi
            else
              echo "Download failed or file too small, retrying..."
              rm -f godot.zip
            fi
            
            # Add a delay before retry
            if [ "$SUCCESS" = false ] && [ $DOWNLOAD_ATTEMPTS -lt $MAX_ATTEMPTS ]; then
              sleep 10
            fi
          done
          
          # If direct download failed, try Homebrew as fallback
          if [ "$SUCCESS" = false ]; then
            echo "Direct download failed after $MAX_ATTEMPTS attempts."
            echo "Falling back to Homebrew installation..."
            brew install --cask godot-mono
            
            if [ -d "/Applications/Godot_mono.app" ]; then
              echo "Godot Mono installed via Homebrew"
              SUCCESS=true
            else
              echo "Homebrew installation failed too. Looking for existing Godot installation..."
              
              if [ -d "/Applications/Godot.app" ]; then
                echo "Found standard Godot installation, will use this but C# support may be limited"
                # Try to get a symlink to the standard version
                ln -s /Applications/Godot.app /Applications/Godot_mono.app
                SUCCESS=true
              fi
            fi
          else
            # Install from the successfully downloaded ZIP
            echo "Extracting Godot Mono from ZIP..."
            unzip -o godot.zip
            
            # Move it to Applications and add to PATH
            if [ -d "Godot_mono.app" ]; then
              mv "Godot_mono.app" /Applications/
              echo "Moved Godot_mono.app to /Applications/"
            else
              # Look for alternative directory structure
              find . -name "*.app" -type d | head -1 | xargs -I{} mv {} /Applications/Godot_mono.app
              echo "Moved found .app to /Applications/Godot_mono.app"
            fi
          fi
          
          # Add to PATH and get version info
          echo "/Applications/Godot_mono.app/Contents/MacOS" >> $GITHUB_PATH
          
          # Verify installation
          if [ -f "/Applications/Godot_mono.app/Contents/MacOS/Godot" ]; then
            echo "Godot executable exists at expected path"
            echo "Getting version info..."
            /Applications/Godot_mono.app/Contents/MacOS/Godot --version || echo "Version command failed but continuing"
            
            # Even if version command fails, try to set environment variables
            GODOT_VERSION="4.2"
            GODOT_FULL_VERSION="4.2.2"
            echo "Assuming Godot version: $GODOT_FULL_VERSION (using $GODOT_VERSION for templates)"
            echo "godot_version=$GODOT_VERSION" >> $GITHUB_ENV
            echo "godot_full_version=$GODOT_FULL_VERSION" >> $GITHUB_ENV
          else
            echo "ERROR: Godot executable not found at expected path"
            echo "Listing Applications directory content:"
            ls -la /Applications/
            exit 1
          fi

      - name: Build Mono Solutions
        run: |
          echo "Building Mono solutions..."
          # Check if Godot has Mono support
          /Applications/Godot_mono.app/Contents/MacOS/Godot --version | grep -i "mono" || echo "WARNING: This Godot version might not have Mono support"
          
          # Try building solutions with explicit path to Godot
          /Applications/Godot_mono.app/Contents/MacOS/Godot --headless --build-solutions || true
          
          # Check if C# assemblies exist
          find . -name "*.dll" | grep -v /\.mono/ || echo "No compiled C# assemblies found"
          
          # If no C# assemblies, try configuring the project for non-C# export
          if [ $(find . -name "*.dll" | grep -v /\.mono/ | wc -l) -eq 0 ]; then
            echo "No C# assemblies found, configuring project for non-C# export"
            # Create a simple project.godot addition that disables C# for export
            if [ -f "project.godot" ]; then
              # Make backup
              cp project.godot project.godot.bak
              # Add config to disable mono
              echo -e "\n[mono]\n\nexport/include_scripts=false\n" >> project.godot
              echo "Modified project.godot to disable mono for export"
            fi
          fi

      - name: Download and install templates
        run: |
          # Define all possible template directories
          TEMPLATE_DIRS=(
            "~/.local/share/godot/export_templates/${godot_version}.stable"
            "~/Library/Application Support/Godot/export_templates/${godot_version}.stable"
            "~/Library/Application Support/Godot/export_templates/${godot_full_version}"
          )
          
          # Create all template directories
          for DIR in "${TEMPLATE_DIRS[@]}"; do
            DIR=$(eval echo "$DIR")
            echo "Creating template directory: $DIR"
            mkdir -p "$DIR"
          done
          
          # Try multiple template sources and formats
          TEMPLATE_URLS=(
            "https://github.com/godotengine/godot/releases/download/${godot_version}-stable/Godot_v${godot_version}-stable_export_templates.tpz"
            "https://github.com/godotengine/godot/releases/download/${godot_version}.0-stable/Godot_v${godot_version}.0-stable_export_templates.tpz"
            "https://downloads.tuxfamily.org/godotengine/${godot_version}/Godot_v${godot_version}-stable_export_templates.tpz"
            "https://github.com/godotengine/godot-builds/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz"
          )
          
          # Try downloading templates
          for URL in "${TEMPLATE_URLS[@]}"; do
            echo "Trying to download templates from: $URL"
            if curl -L --connect-timeout 30 --retry 3 --retry-delay 5 "$URL" -o templates.tpz; then
              # Check if it's a valid zip file
              if unzip -t templates.tpz > /dev/null 2>&1; then
                echo "Successfully downloaded templates from $URL"
                break
              else
                echo "Downloaded file is not a valid zip archive, trying next source..."
                rm templates.tpz
              fi
            else
              echo "Failed to download from $URL, trying next source..."
            fi
          done
          
          # Final check and installation
          if [ -f templates.tpz ] && unzip -t templates.tpz > /dev/null 2>&1; then
            echo "Installing templates..."
            unzip -o templates.tpz -d .
            
            # Copy templates to all possible locations
            for DIR in "${TEMPLATE_DIRS[@]}"; do
              DIR=$(eval echo "$DIR")
              echo "Installing templates to: $DIR"
              
              # Copy from templates directory if it exists
              if [ -d "templates" ]; then
                cp -r templates/* "$DIR/"
                
                # Directly extract ios.zip from templates if needed
                if [ -f "templates/ios.zip" ]; then
                  echo "Found ios.zip in templates directory"
                  cp templates/ios.zip "$DIR/"
                fi
              fi
              
              # Also copy loose files in case templates directory doesn't exist
              cp -f *.zip "$DIR/" 2>/dev/null || true
              cp -f *.tpz "$DIR/" 2>/dev/null || true
            done
            
            # Create symlinks between different template directories for good measure
            for DIR in "${TEMPLATE_DIRS[@]}"; do
              DIR=$(eval echo "$DIR")
              if [ -d "$DIR" ]; then
                echo "Contents of $DIR:"
                ls -la "$DIR/"
              fi
            done
            
            # Try to manually extract iOS templates if they're inside another zip
            if [ -f "templates/ios.zip" ]; then
              for DIR in "${TEMPLATE_DIRS[@]}"; do
                DIR=$(eval echo "$DIR")
                cp templates/ios.zip "$DIR/" || true
              done
            elif [ -f "templates.tpz" ]; then
              echo "Extracting iOS template from templates.tpz"
              mkdir -p temp_extract
              unzip -j templates.tpz "*ios*" -d temp_extract || true
              if [ -f "temp_extract/ios.zip" ]; then
                for DIR in "${TEMPLATE_DIRS[@]}"; do
                  DIR=$(eval echo "$DIR")
                  cp temp_extract/ios.zip "$DIR/" || true
                done
              fi
              rm -rf temp_extract
            fi
            
            # Debug - List all template directories
            echo "Template directories contents:"
            for DIR in "${TEMPLATE_DIRS[@]}"; do
              DIR=$(eval echo "$DIR")
              echo "Contents of $DIR:"
              ls -la "$DIR/" || true
            done
          else
            echo "Failed to obtain valid export templates after multiple attempts."
            exit 1
          fi
      
      - name: Create export_presets.cfg if missing
        run: |
          if [ ! -f export_presets.cfg ]; then
            echo "Creating minimal export_presets.cfg for iOS"
            cat > export_presets.cfg << 'EOFMARKER'
          [preset.0]
          
          name="iOS"
          platform="iOS"
          runnable=true
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/ios/GodotPacman.xcarchive"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          
          [preset.0.options]
          
          custom_template/debug=""
          custom_template/release=""
          application/app_store_team_id="12345678AB"  # Dummy ID to pass validation
          application/provisioning_profile_uuid_debug=""
          application/code_sign_identity_debug=""
          application/export_method_debug=1  # Set to development
          application/provisioning_profile_uuid_release=""
          application/code_sign_identity_release=""
          application/export_method_release=0
          application/targeted_device_family=2
          application/bundle_identifier="com.yourusername.godotpacman"
          application/signature=""
          application/short_version="1.0"
          application/version="1.0"
          application/icon_76x76=""
          application/icon_152x152=""
          application/icon_1024x1024=""
          capabilities/access_wifi=false
          capabilities/push_notifications=false
          user_data/accessible_from_files_app=false
          user_data/accessible_from_itunes_sharing=false
          privacy/camera_usage_description=""
          privacy/microphone_usage_description=""
          privacy/photolibrary_usage_description=""
          orientation/portrait=true
          orientation/landscape_left=false
          orientation/landscape_right=false
          orientation/portrait_upside_down=false
          EOFMARKER
            echo "Created export_presets.cfg file"
          else
            echo "export_presets.cfg already exists"
          fi
          cat export_presets.cfg
          
      - name: Godot export debug info
        run: |
          echo "Installed Godot version:"
          godot --version
          
          echo "Looking for template locations:"
          find ~ -name "export_templates" -type d | xargs ls -la || true
          
          echo "Checking specific template paths:"
          ls -la ~/.local/share/godot/export_templates/ 2>/dev/null || echo "Path not found"
          ls -la ~/Library/Application\ Support/Godot/export_templates/ 2>/dev/null || echo "Path not found"
          
          echo "Current directory content:"
          ls -la
          
      - name: Export iOS XCArchive
        run: |
          mkdir -p build/ios
          echo "Exporting XCArchive using --export-debug..."
          # Try export with fallbacks for different Godot versions and parameters
          export_success=false
          
          # Try with explicit path and export-debug
          echo "Trying export-debug..."
          /Applications/Godot_mono.app/Contents/MacOS/Godot --headless --export-debug "iOS" "build/ios/GodotPacman.xcarchive" && export_success=true
          
          # If that failed, try with plain export
          if [ "$export_success" = false ]; then
            echo "export-debug failed, trying with plain export..."
            /Applications/Godot_mono.app/Contents/MacOS/Godot --headless --export "iOS" "build/ios/GodotPacman.xcarchive" && export_success=true
          fi
          
          # If still failed, try finding a different Godot executable
          if [ "$export_success" = false ]; then
            echo "Trying to find alternate Godot executable..."
            find /Applications -name "Godot*" -type d | while read godot_app; do
              echo "Trying with $godot_app/Contents/MacOS/Godot"
              $godot_app/Contents/MacOS/Godot --headless --export-debug "iOS" "build/ios/GodotPacman.xcarchive" && export_success=true && break
            done
          fi
          
          if [ -d "build/ios/GodotPacman.xcarchive" ]; then
            echo "Successfully created XCArchive!"
            # Create a README with signing instructions
            cat > build/ios/SIGNING_INSTRUCTIONS.txt << 'EOF'
            iOS Export - Signing Instructions

            This archive contains both an XCArchive and an unsigned IPA.

            To sign with your Apple Developer account:

            1. Open Xcode on a Mac.
            2. Open Window > Organizer.
            3. Drag the GodotPacman.xcarchive into the Organizer.
            4. Click "Distribute App".
            5. Select "App Store Connect" or "Ad Hoc" distribution.
            6. Follow the signing steps with your Apple Developer credentials.
            EOF
          else
            echo "XCArchive export failed."
            # Create a placeholder directory
            mkdir -p build/ios/GodotPacman.xcarchive
            echo "Export failed. See logs for details." > build/ios/GodotPacman.xcarchive/README.txt
          fi
          
      - name: Generate IPA from XCArchive
        run: |
          if [ -d "build/ios/GodotPacman.xcarchive" ]; then
            echo "Generating unsigned IPA from XCArchive..."
            cd build/ios
            
            # For Godot 4.x, the app location might be different
            APP_PATH=""
            if [ -d "GodotPacman.xcarchive/Products/Applications" ]; then
              APP_PATH="GodotPacman.xcarchive/Products/Applications"
            elif [ -d "GodotPacman.xcarchive/Products/Apps" ]; then
              APP_PATH="GodotPacman.xcarchive/Products/Apps"
            fi
            
            if [ -n "$APP_PATH" ]; then
              # Find the app file (should be only one)
              APP_FILE=$(ls "$APP_PATH"/*.app 2>/dev/null | head -1)
              
              if [ -n "$APP_FILE" ]; then
                echo "Found app at: $APP_FILE"
                mkdir -p Payload
                cp -r "$APP_FILE" Payload/
                zip -r GodotPacman.ipa Payload
                rm -rf Payload
                echo "Created unsigned IPA successfully."
              else
                echo "Could not find .app file in XCArchive."
              fi
            else
              echo "Could not find Applications directory in XCArchive."
            fi
            
            cd ../..
          else
            echo "No XCArchive found, cannot create IPA."
          fi
          
      - name: Create project copy for manual export
        run: |
          # Create a clean copy of the project for manual export later
          mkdir -p build/ios/project_files
          cp -r *.tscn *.gd *.import project.godot export_presets.cfg assets/ build/ios/project_files/ 2>/dev/null || true
          echo "Project files copied for manual export if needed."
          
      - name: Package all exports
        run: |
          cd build/ios
          zip -r GodotPacman_iOS_Export.zip * -x "*.DS_Store" -x "*.git*"
          cd ../..
          
      - name: List exported files
        run: |
          echo "Export directory contents:"
          ls -la build/ios || echo "No files found in build/ios"
          
          if [ ! -f "build/ios/GodotPacman.ipa" ] && [ ! -d "build/ios/GodotPacman.xcarchive" ]; then
            echo "No export files were created. Creating a placeholder file for artifact upload."
            mkdir -p build/ios
            echo "Export failed. Please check the logs for details." > build/ios/export_failed.txt
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios
          retention-days: 14

      - name: Import project resources
        run: |
          echo "Importing project resources..."
          # Create .godot directory first if it doesn't exist
          mkdir -p .godot
          
          # Run Godot to scan and import resources
          /Applications/Godot_mono.app/Contents/MacOS/Godot --headless --editor --quit --accept-md5-signatures
          
          # Alternative import command if the above fails
          if [ ! -d ".godot/imported" ] && [ ! -d ".import" ]; then
            echo "First import attempt failed, trying alternative method..."
            /Applications/Godot_mono.app/Contents/MacOS/Godot --headless --export-pack --accept-md5-signatures --tests-exit
          fi
          
          # Check if import directories were created
          if [ -d ".godot/imported" ] || [ -d ".import" ]; then
            echo "Resources imported successfully"
            # List some imported files for verification
            find .godot/imported -type f 2>/dev/null | head -n 5 || true
            find .import -type f 2>/dev/null | head -n 5 || true
          else
            echo "Warning: Import directories not found"
            # Create placeholder directories to avoid further errors
            mkdir -p .godot/imported
            mkdir -p .import
          fi